### ISSUE TITLE
Windows pipenv install does not install packages

### ISSUE THREAD

**Issue by madbuda** [philippnormann/chia-monitor#12]
I ended up having to `pipenv shell` then run 

`pip install bitstring==3.1.7 chiabip158==1.0 chiapos==1.0.3 chiavdf==1.0.2 clvm==0.9.7 clvm-rs==0.1.8 clvm-tools==0.4.3 concurrent-log-handler==0.9.19 dnspython==2.1.0 keyring==23.0.1 keyrings.cryptfile==1.3.4 setproctitle==1.2.2 sortedcontainers==2.3.0 websockets==8.1.0 aiohttp==3.7.4 click==7.1.2`

Quick PR to add requirements.txt and update readme https://github.com/philippnormann/chia-monitor/pull/10

**Comment by nvg58** [comment]
yes. I got the same issues. here is the error logs:

```PS C:\Users\Admin\chia-monitor> pipenv run python -m monitor
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\admin\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\chia-monitor\monitor\__main__.py", line 11, in <module>
    from monitor.collectors import RpcCollector, WsCollector
  File "C:\Users\Admin\chia-monitor\monitor\collectors\__init__.py", line 2, in <module>
    from monitor.collectors.rpc_collector import RpcCollector
  File "C:\Users\Admin\chia-monitor\monitor\collectors\rpc_collector.py", line 11, in <module>
    from chia.rpc.farmer_rpc_client import FarmerRpcClient
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\chia\rpc\farmer_rpc_client.py", line 3, in <module>
    from chia.rpc.rpc_client import RpcClient
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\chia\rpc\rpc_client.py", line 7, in <module>
    from chia.server.server import ssl_context_for_client
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\chia\server\server.py", line 19, in <module>
    from chia.protocols.shared_protocol import protocol_version
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\chia\protocols\shared_protocol.py", line 6, in <module>
    from chia.util.streamable import Streamable, streamable
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\chia\util\streamable.py", line 12, in <module>
    from blspy import G1Element, G2Element, PrivateKey
ModuleNotFoundError: No module named 'blspy'```

**Comment by nvg58** [comment]
I am seeing that @philippnormann using some lib from chia lib but not add it to Pipfile.lock

**Comment by philippnormann** [comment]
Thanks for reporting the issue! I will setup a Windows VM later to debug this in detail.

**Comment by philippnormann** [comment]
Hey @nvg58 and @madbuda, could you please check if the latest update to the Pipfile resolved this problem?

**Comment by nvg58** [comment]
thanks @philippnormann it works now. But I still got the errors in issue #15
