### ISSUE TITLE
Crash when running in windows

### ISSUE THREAD

**Issue by nvg58** [philippnormann/chia-monitor#15]
- I have 5 remote harvesters connecting to a farmer.

Here is the error logs:

```
Traceback (most recent call last):
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 99, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 228, in _handle_exception
    raise error
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 81, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlite3.IntegrityError: UNIQUE constraint failed: farming_info_events.ts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\admin\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\chia-monitor\monitor\__main__.py", line 112, in <module>
    asyncio.run(aggregator(exporter, notifier))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Admin\chia-monitor\monitor\__main__.py", line 65, in aggregator
    await persist_event(event)
  File "C:\Users\Admin\chia-monitor\monitor\__main__.py", line 36, in persist_event
    await db_session.commit()
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 333, in commit
    return await greenlet_spawn(self.sync_session.commit)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 129, in greenlet_spawn
    result = context.switch(value)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\orm\session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\orm\session.py", line 3298, in flush
    self._flush(objects)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\orm\session.py", line 3438, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\orm\session.py", line 3398, in _flush
    flush_context.execute()
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\orm\persistence.py", line 242, in save_obj
    _emit_insert_statements(
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\orm\persistence.py", line 1094, in _emit_insert_statements
    c = connection._execute_20(
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\engine\base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\engine\base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\engine\base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\engine\base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 99, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 228, in _handle_exception
    raise error
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 81, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: farming_info_events.ts
[SQL: INSERT INTO farming_info_events (ts, challenge_hash, signage_point, passed_filter, proofs, total_plots) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('2021-07-12 17:27:17.517614', '0x06570eeaf05dee5c1255a107302bc7f62ae09f1a54db17fcf8727113e17e96d0', '0xc47c18b5091fa835e2f3632b01f91fb7a17874e7d5119d9b66d38ca2e5c5fff8', 1, 0, 778)]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
2021-07-12T17:27:17.743 ←[31mERROR ←[0m Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002523B232970>←[0m
2021-07-12T17:27:17.743 ←[31mERROR ←[0m Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002523B20C280>←[0m
2021-07-12T17:27:17.745 ←[31mERROR ←[0m Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002523B20C7C0>←[0m
2021-07-12T17:27:17.745 ←[31mERROR ←[0m Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002523B20CFA0>←[0m
2021-07-12T17:27:17.745 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002523B232EB0>
transport: <_ProactorSocketTransport fd=1160 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function ClientResponse.__del__ at 0x0000025239309940>
Traceback (most recent call last):
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiohttp\client_reqrep.py", line 803, in __del__
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiohttp\connector.py", line 170, in release
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiohttp\connector.py", line 650, in _release
  File "C:\Users\Admin\.virtualenvs\chia-monitor--AE16joc\lib\site-packages\aiohttp\client_proto.py", line 63, in close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-12T17:27:17.748 ←[31mERROR ←[0m Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002523B28B400>, 680519.984), (<aiohttp.client_proto.ResponseHandler object at 0x000002523B244B20>, 680519.984)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002523B20C2B0>←[0m
2021-07-12T17:27:17.748 ←[31mERROR ←[0m Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002523B28B520>, 680521.125)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002523B20CC40>←[0m
2021-07-12T17:27:17.748 ←[31mERROR ←[0m Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002523B2CC9A0>, 680520.89), (<aiohttp.client_proto.ResponseHandler object at 0x000002523B2B4760>, 680520.89), (<aiohttp.client_proto.ResponseHandler object at 0x000002523B28B9A0>, 680520.921)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002523B20C3A0>←[0m
2021-07-12T17:27:17.749 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002523B20C970>
transport: <_ProactorSocketTransport fd=1128 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000025237288E50>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-12T17:27:17.750 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002523B20CCA0>
transport: <_ProactorSocketTransport fd=1248 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000025237288E50>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-12T17:27:17.752 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002523B232310>
transport: <_ProactorSocketTransport fd=1152 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000025237288E50>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-12T17:27:17.754 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002523B2327C0>
transport: <_ProactorSocketTransport fd=1156 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000025237288E50>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-12T17:27:17.755 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002523B25AD30>
transport: <_ProactorSocketTransport fd=1252 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000025237288E50>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-12T17:27:17.757 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002523B24FF10>
transport: <_ProactorSocketTransport fd=1516 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000025237288E50>
Traceback (most recent call last):
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\users\admin\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
```

**Comment by micgogo** [comment]
same issue here on windows

**Comment by philippnormann** [comment]
Thanks for reporting the issue! I will setup a Windows VM later to debug this in detail.

**Comment by philippnormann** [comment]
The bug was caused by farming events that were collected at the same timestamp, which caused an index collision when we tried to insert those events into the DB.The latest commit https://github.com/philippnormann/chia-monitor/commit/afbd24f580547bc4335e6c9aef966d7bdbd34715 should fix this issue. 

@nvg58 and @micgogo could you please confirm that the latest update fixes this issue for you as well?

**Comment by micgogo** [comment]
Yes new version has fixed issue
