### ISSUE TITLE
Crashing with this exception sqlite3.IntegrityError: UNIQUE constraint failed: signage_point_events.ts

### ISSUE THREAD

**Issue by charnet3d** [philippnormann/chia-monitor#29]
I'm getting this crash pretty consistently:

```
2021-07-20T08:59:29.369 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:29.369 ←[32mINFO  ←[0m 🏷️  Price in USD: 169.06←[0m
2021-07-20T08:59:29.369 ←[32mINFO  ←[0m 🏷️  Price in EUR: 143.44←[0m
2021-07-20T08:59:29.369 ←[32mINFO  ←[0m 🏷️  Price in BTC: 0.00566428←[0m
2021-07-20T08:59:29.369 ←[32mINFO  ←[0m 🏷️  Price in ETH: 0.09555288←[0m
2021-07-20T08:59:31.291 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:31.291 ←[32mINFO  ←[0m 🌾 OG Plot Count: 186←[0m
2021-07-20T08:59:31.291 ←[32mINFO  ←[0m 🌾 Portable Plot Count: 43←[0m
2021-07-20T08:59:31.292 ←[32mINFO  ←[0m 🧺 OG Plot Size: 18.411 TiB←[0m
2021-07-20T08:59:31.292 ←[32mINFO  ←[0m 🧺 Portable Plot Size: 4.257 TiB←[0m
2021-07-20T08:59:31.292 ←[32mINFO  ←[0m 🖥️  Host: 127.0.0.1←[0m
2021-07-20T08:59:31.470 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:31.471 ←[32mINFO  ←[0m 🌾 OG Plot Count: 81←[0m
2021-07-20T08:59:31.471 ←[32mINFO  ←[0m 🌾 Portable Plot Count: 0←[0m
2021-07-20T08:59:31.471 ←[32mINFO  ←[0m 🧺 OG Plot Size: 8.018 TiB←[0m
2021-07-20T08:59:31.471 ←[32mINFO  ←[0m 🧺 Portable Plot Size: 0.000 MiB←[0m
2021-07-20T08:59:31.471 ←[32mINFO  ←[0m 🖥️  Host: 192.168.2.206←[0m
2021-07-20T08:59:31.649 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:31.649 ←[32mINFO  ←[0m 🌾 OG Plot Count: 92←[0m
2021-07-20T08:59:31.649 ←[32mINFO  ←[0m 🌾 Portable Plot Count: 12←[0m
2021-07-20T08:59:31.650 ←[32mINFO  ←[0m 🧺 OG Plot Size: 9.107 TiB←[0m
2021-07-20T08:59:31.650 ←[32mINFO  ←[0m 🧺 Portable Plot Size: 1.188 TiB←[0m
2021-07-20T08:59:31.650 ←[32mINFO  ←[0m 🖥️  Host: 192.168.2.205←[0m
2021-07-20T08:59:31.825 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:31.825 ←[32mINFO  ←[0m 🟣 Current Points: 114←[0m
2021-07-20T08:59:31.825 ←[32mINFO  ←[0m 📈 Pool Difficulty: 4←[0m
2021-07-20T08:59:31.826 ←[32mINFO  ←[0m 🟡 Pool Found: 394←[0m
2021-07-20T08:59:31.826 ←[32mINFO  ←[0m 🟢 Pool Acknowledged: 384←[0m
2021-07-20T08:59:31.826 ←[32mINFO  ←[0m 🟡 Pool Found Last 24H: 394←[0m
2021-07-20T08:59:31.826 ←[32mINFO  ←[0m 🟢 Pool Acknowledged Last 24H: 384←[0m
2021-07-20T08:59:31.826 ←[32mINFO  ←[0m ❌ Pool Errors 24h: 0←[0m
2021-07-20T08:59:32.001 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:32.002 ←[32mINFO  ←[0m 📶 Full Node Peer Count: 27←[0m
2021-07-20T08:59:32.002 ←[32mINFO  ←[0m 📶 Farmer Peer Count: 1←[0m
2021-07-20T08:59:32.002 ←[32mINFO  ←[0m 📶 Harvester Peer Count: 3←[0m
2021-07-20T08:59:32.147 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:32.147 ←[32mINFO  ←[0m 💰 Total Balance: x.xxxxx XCH←[0m
2021-07-20T08:59:32.147 ←[32mINFO  ←[0m 💸 Total Farmed: x.xxxxx XCH←[0m
2021-07-20T08:59:32.325 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:32.325 ←[32mINFO  ←[0m 💾 Current Netspace: 30.066 EiB←[0m
2021-07-20T08:59:32.325 ←[32mINFO  ←[0m 📈 Farming Difficulty: 2464←[0m
2021-07-20T08:59:32.325 ←[32mINFO  ←[0m 🏔️  Peak Height: 597510←[0m
2021-07-20T08:59:32.325 ←[32mINFO  ←[0m 🔄 Synced: Yes←[0m
2021-07-20T08:59:32.325 ←[32mINFO  ←[0m 🏔️ Syncing Peak Height: 0←[0m
2021-07-20T08:59:32.326 ←[32mINFO  ←[0m 🏔️ Syncing Progress Height: 0←[0m
2021-07-20T08:59:38.213 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:38.213 ←[32mINFO  ←[0m 🔏 Signage Point Index: xx←[0m
2021-07-20T08:59:38.213 ←[32mINFO  ←[0m 🎰 Challenge Hash: xxx←[0m
2021-07-20T08:59:38.213 ←[32mINFO  ←[0m ⌛ Signage Point: xxx←[0m
2021-07-20T08:59:38.603 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:38.603 ←[32mINFO  ←[0m 🎰 Challenge Hash: xxx←[0m
2021-07-20T08:59:38.603 ←[32mINFO  ←[0m ⌛ Signage Point: xxx←[0m
2021-07-20T08:59:38.603 ←[32mINFO  ←[0m 🌾 Plot Count: 81←[0m
2021-07-20T08:59:38.603 ←[32mINFO  ←[0m 🔎 Passed Filter: 1←[0m
2021-07-20T08:59:38.604 ←[32mINFO  ←[0m ✅ Total Proofs found: 0←[0m
2021-07-20T08:59:42.031 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:42.031 ←[32mINFO  ←[0m 🎰 Challenge Hash: xxx←[0m
2021-07-20T08:59:42.031 ←[32mINFO  ←[0m ⌛ Signage Point: xxx←[0m
2021-07-20T08:59:42.032 ←[32mINFO  ←[0m 🌾 Plot Count: 229←[0m
2021-07-20T08:59:42.032 ←[32mINFO  ←[0m 🔎 Passed Filter: 1←[0m
2021-07-20T08:59:42.032 ←[32mINFO  ←[0m ✅ Total Proofs found: 0←[0m
2021-07-20T08:59:42.322 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:42.322 ←[32mINFO  ←[0m 🎰 Challenge Hash: xxx←[0m
2021-07-20T08:59:42.322 ←[32mINFO  ←[0m ⌛ Signage Point: xxx←[0m
2021-07-20T08:59:42.323 ←[32mINFO  ←[0m 🌾 Plot Count: 104←[0m
2021-07-20T08:59:42.323 ←[32mINFO  ←[0m 🔎 Passed Filter: 1←[0m
2021-07-20T08:59:42.323 ←[32mINFO  ←[0m ✅ Total Proofs found: 0←[0m
2021-07-20T08:59:42.824 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:42.824 ←[32mINFO  ←[0m 🔏 Signage Point Index: xx←[0m
2021-07-20T08:59:42.825 ←[32mINFO  ←[0m 🎰 Challenge Hash: xxx←[0m
2021-07-20T08:59:42.825 ←[32mINFO  ←[0m ⌛ Signage Point: xxx←[0m
2021-07-20T08:59:46.795 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:46.796 ←[32mINFO  ←[0m 🔏 Signage Point Index: xx←[0m
2021-07-20T08:59:46.800 ←[32mINFO  ←[0m 🎰 Challenge Hash: xxx←[0m
2021-07-20T08:59:46.801 ←[32mINFO  ←[0m ⌛ Signage Point: xxx←[0m
2021-07-20T08:59:49.916 ←[32mINFO  ←[0m ----------------------------------------------------------------←[0m
2021-07-20T08:59:49.916 ←[32mINFO  ←[0m 🔏 Signage Point Index: xx←[0m
2021-07-20T08:59:49.920 ←[32mINFO  ←[0m 🎰 Challenge Hash: xxx←[0m
2021-07-20T08:59:49.921 ←[32mINFO  ←[0m ⌛ Signage Point: xxx←[0m
Traceback (most recent call last):
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 99, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 228, in _handle_exception
    raise error
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 81, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlite3.IntegrityError: UNIQUE constraint failed: signage_point_events.ts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Programs\chia-monitor\monitor\__main__.py", line 136, in <module>
    asyncio.run(aggregator(exporter, notifier))
  File "c:\python\python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Programs\chia-monitor\monitor\__main__.py", line 77, in aggregator
    await persist_event(event)
  File "D:\Programs\chia-monitor\monitor\__main__.py", line 39, in persist_event
    await db_session.commit()
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 333, in commit
    return await greenlet_spawn(self.sync_session.commit)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 129, in greenlet_spawn
    result = context.switch(value)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\orm\session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\orm\session.py", line 829, in commit
    self._prepare_impl()
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\orm\session.py", line 808, in _prepare_impl
    self.session.flush()
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\orm\session.py", line 3298, in flush
    self._flush(objects)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\orm\session.py", line 3438, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\util\langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\orm\session.py", line 3398, in _flush
    flush_context.execute()
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 456, in execute
    rec.execute(self)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\orm\persistence.py", line 242, in save_obj
    _emit_insert_statements(
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\orm\persistence.py", line 1094, in _emit_insert_statements
    c = connection._execute_20(
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\engine\base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\engine\base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\engine\base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\engine\base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
    raise exception
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 99, in execute
    self._adapt_connection._handle_exception(error)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 228, in _handle_exception
    raise error
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 81, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: signage_point_events.ts
[SQL: INSERT INTO signage_point_events (ts, challenge_hash, signage_point, signage_point_index) VALUES (?, ?, ?, ?)]
[parameters: ('2021-07-20 08:59:38.943587', 'xxx', 'xxx', xx)]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020C9568D820>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "c:\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "c:\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2021-07-20T08:59:52.619 ←[31mERROR ←[0m Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020C9820ECA0>←[0m
2021-07-20T08:59:52.619 ←[31mERROR ←[0m Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020C981F7DC0>←[0m
2021-07-20T08:59:52.621 ←[31mERROR ←[0m Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020C981E35B0>←[0m
2021-07-20T08:59:52.624 ←[31mERROR ←[0m Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020C9820E220>←[0m
2021-07-20T08:59:52.624 ←[31mERROR ←[0m Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000020C9820E4F0>←[0m
2021-07-20T08:59:52.625 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000020C981F79D0>
transport: <_ProactorSocketTransport fd=1040 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function ClientResponse.__del__ at 0x0000020C97687C10>
Traceback (most recent call last):
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiohttp\client_reqrep.py", line 803, in __del__
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiohttp\connector.py", line 170, in release
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiohttp\connector.py", line 650, in _release
  File "C:\Users\Sam\.virtualenvs\chia-monitor-MiorTuYS\lib\site-packages\aiohttp\client_proto.py", line 63, in close
  File "c:\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-20T08:59:52.660 ←[31mERROR ←[0m Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000020C982703A0>, 451174.968), (<aiohttp.client_proto.ResponseHandler object at 0x0000020C9823CAC0>, 451175.484)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000020C981E37F0>←[0m
2021-07-20T08:59:52.660 ←[31mERROR ←[0m Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000020C98270460>, 451175.156)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000020C9820E490>←[0m
2021-07-20T08:59:52.660 ←[31mERROR ←[0m Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x0000020C982708E0>, 451174.984), (<aiohttp.client_proto.ResponseHandler object at 0x0000020C9828B5E0>, 451174.984), (<aiohttp.client_proto.ResponseHandler object at 0x0000020C9828BB80>, 451174.984)]']
connector: <aiohttp.connector.TCPConnector object at 0x0000020C9820E940>←[0m
2021-07-20T08:59:52.661 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000020C9820E130>
transport: <_ProactorSocketTransport fd=1016 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000020C9562C700>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-20T08:59:52.672 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000020C981F7430>
transport: <_ProactorSocketTransport fd=1108 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000020C9562C700>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-20T08:59:52.678 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000020C9820EA00>
transport: <_ProactorSocketTransport fd=1036 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000020C9562C700>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-20T08:59:52.688 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000020C98207D30>
transport: <_ProactorSocketTransport fd=1136 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000020C9562C700>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-20T08:59:52.694 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000020C9820E280>
transport: <_ProactorSocketTransport fd=1132 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000020C9562C700>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
2021-07-20T08:59:52.706 ←[31mERROR ←[0m Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000020C981F77F0>
transport: <_ProactorSocketTransport fd=1048 read=<_OverlappedFuture cancelled>>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 684, in _process_write_backlog
    self._transport.write(chunk)
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 359, in write
    self._loop_writing(data=bytes(data))
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 395, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
AttributeError: 'NoneType' object has no attribute 'send'←[0m
Exception ignored in: <function _SSLProtocolTransport.__del__ at 0x0000020C9562C700>
Traceback (most recent call last):
  File "c:\python\python39\lib\asyncio\sslproto.py", line 321, in __del__
  File "c:\python\python39\lib\asyncio\sslproto.py", line 316, in close
  File "c:\python\python39\lib\asyncio\sslproto.py", line 593, in _start_shutdown
  File "c:\python\python39\lib\asyncio\sslproto.py", line 598, in _write_appdata
  File "c:\python\python39\lib\asyncio\sslproto.py", line 706, in _process_write_backlog
  File "c:\python\python39\lib\asyncio\sslproto.py", line 720, in _fatal_error
  File "c:\python\python39\lib\asyncio\proactor_events.py", line 151, in _force_close
  File "c:\python\python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "c:\python\python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed

```

**Comment by philippnormann** [comment]
Do you still run into this error using the latest version?

**Comment by charnet3d** [comment]
Thanks, I updated my repo, I'll let you know if anything comes up.

**Comment by charnet3d** [comment]
I think this has been fixed because I'm not getting the error anymore.
Closing the issue.
