### ISSUE TITLE
Startup fails sqlite3.IntegrityError: UNIQUE constraint failed

### ISSUE THREAD

**Issue by funstuk** [philippnormann/chia-monitor#31]
Hi!
Errors occur after pipenv run python -m monitor.
Unable to start, latest version. 

```
root@chia-ubuntu:~/chia-monitor# pipenv run python -m monitor
2021-07-23T11:19:56.669 INFO   🔌 Creating RPC Collector...
2021-07-23T11:19:56.687 INFO   🔌 Creating WebSocket Collector...
2021-07-23T11:19:56.694 INFO   🔌 Creating Price Collector...
2021-07-23T11:19:56.694 INFO   🚀 Starting monitoring loop!
2021-07-23T11:19:56.707 INFO   ----------------------------------------------------------------
2021-07-23T11:19:56.707 INFO   💾 Current Netspace: 31.223 EiB
2021-07-23T11:19:56.707 INFO   📈 Farming Difficulty: 2544
2021-07-23T11:19:56.707 INFO   🏔️  Peak Height: 611608
2021-07-23T11:19:56.707 INFO   🔄 Synced: True
2021-07-23T11:19:56.751 INFO   ----------------------------------------------------------------
2021-07-23T11:19:56.751 INFO   🟣 Current Points: 1041
2021-07-23T11:19:56.752 INFO   📈 Pool Difficulty: 34
2021-07-23T11:19:56.752 INFO   🟡 Pool Found: 11179
2021-07-23T11:19:56.752 INFO   🟢 Pool Acknowledged: 11193
2021-07-23T11:19:56.752 INFO   🟡 Pool Found Last 24H: 11179
2021-07-23T11:19:56.752 INFO   🟢 Pool Acknowledged Last 24H: 11193
2021-07-23T11:19:56.753 INFO   ❌ Pool Errors 24h: 0
2021-07-23T11:19:56.761 INFO   ----------------------------------------------------------------
2021-07-23T11:19:56.761 INFO   🌾 OG Plot Count: 0
2021-07-23T11:19:56.761 INFO   🌾 Portable Plot Count: 396
2021-07-23T11:19:56.762 INFO   🧺 OG Plot Size: 0.000 MiB
2021-07-23T11:19:56.762 INFO   🧺 Portable Plot Size: 39.193 TiB
2021-07-23T11:19:56.762 INFO   🖥️  Host: 192.168.1.1
2021-07-23T11:19:56.770 INFO   ----------------------------------------------------------------
2021-07-23T11:19:56.770 INFO   🌾 OG Plot Count: 0
2021-07-23T11:19:56.771 INFO   🌾 Portable Plot Count: 0
2021-07-23T11:19:56.771 INFO   🧺 OG Plot Size: 0.000 MiB
2021-07-23T11:19:56.771 INFO   🧺 Portable Plot Size: 0.000 MiB
2021-07-23T11:19:56.771 INFO   🖥️  Host: 127.0.0.1
2021-07-23T11:19:56.780 INFO   ----------------------------------------------------------------
2021-07-23T11:19:56.780 INFO   🌾 OG Plot Count: 0
2021-07-23T11:19:56.780 INFO   🌾 Portable Plot Count: 844
2021-07-23T11:19:56.780 INFO   🧺 OG Plot Size: 0.000 MiB
2021-07-23T11:19:56.780 INFO   🧺 Portable Plot Size: 83.533 TiB
2021-07-23T11:19:56.780 INFO   🖥️  Host: 192.168.1.1
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 99, in execute
    self._adapt_connection._handle_exception(error)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 228, in _handle_exception
    raise error
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 81, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.IntegrityError: UNIQUE constraint failed: harvester_events.ts, harvester_events.host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/chia-monitor/monitor/__main__.py", line 136, in <module>
    asyncio.run(aggregator(exporter, notifier))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/chia-monitor/monitor/__main__.py", line 77, in aggregator
    await persist_event(event)
  File "/root/chia-monitor/monitor/__main__.py", line 39, in persist_event
    await db_session.commit()
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/session.py", line 333, in commit
    return await greenlet_spawn(self.sync_session.commit)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    result = context.switch(value)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 829, in commit
    self._prepare_impl()
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
    self.session.flush()
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3298, in flush
    self._flush(objects)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3438, in _flush
    transaction.rollback(_capture_exception=True)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 3398, in _flush
    flush_context.execute()
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 242, in save_obj
    _emit_insert_statements(
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1094, in _emit_insert_statements
    c = connection._execute_20(
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 99, in execute
    self._adapt_connection._handle_exception(error)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 228, in _handle_exception
    raise error
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 81, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 69, in await_only
    return current.driver.switch(awaitable)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 122, in greenlet_spawn
    value = await result
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/root/.local/share/virtualenvs/chia-monitor-ToXQE9iy/lib/python3.8/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: harvester_events.ts, harvester_events.host
[SQL: INSERT INTO harvester_events (ts, host, plot_count, portable_plot_count, plot_size, portable_plot_size) VALUES (?, ?, ?, ?, ?, ?)]
[parameters: ('2021-07-23 11:19:56.723106', '192.168.1.1', 0, 844, 0, 91845464709906)]
(Background on this error at: http://sqlalche.me/e/14/gkpj)
2021-07-23T11:19:56.841 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f56acf726a0>
2021-07-23T11:19:56.841 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f56acfce8e0>
2021-07-23T11:19:56.841 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f56acfdcf70>
2021-07-23T11:19:56.841 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f56acf72040>
2021-07-23T11:19:56.841 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f56acf72760>
2021-07-23T11:19:56.842 ERROR  Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f56acf9bfa0>, 76765.947169551), (<aiohttp.client_proto.ResponseHandler object at 0x7f56acf66760>, 76765.952335297)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f56acfdcdf0>
2021-07-23T11:19:56.842 ERROR  Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f56acf4d820>, 76765.957695482), (<aiohttp.client_proto.ResponseHandler object at 0x7f56ac6eee20>, 76765.957754708), (<aiohttp.client_proto.ResponseHandler object at 0x7f56ac712dc0>, 76765.974993511)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f56acf72d00>
```

**Comment by charnet3d** [comment]
@philippnormann The ts primary keys should probably all be removed and autoincrement ids used instead, because those can be repeated in rare cases thus violating the UNIQUE constraint.
