### ISSUE TITLE
Guys, what's the problem? Suddenly report an error

### ISSUE THREAD

**Issue by tangdasan** [philippnormann/chia-monitor#40]
`2021-07-29T18:32:08.471 INFO   🏷️  Price in BTC: 0.0048449
2021-07-29T18:32:08.472 INFO   🏷️  Price in ETH: 0.08444829
2021-07-29T18:32:32.121 INFO   🛑 Shutting down!
2021-07-29T18:32:32.125 ERROR  Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fc02bb335e0>
2021-07-29T18:32:32.125 INFO   👋 Bye!
2021-07-29T18:32:32.157 ERROR  Task exception was never retrieved
future: <Task finished name='Task-11' coro=<WsCollector.task() done, defined at /home/chia/soft/chia-monitor/monitor/collectors/ws_collector.py:78> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/home/chia/soft/chia-monitor/monitor/collectors/ws_collector.py", line 81, in task
    msg = await self.ws.receive_json()
  File "/home/chia/.local/share/virtualenvs/chia-monitor-Iocbb-0M/lib/python3.8/site-packages/aiohttp/client_ws.py", line 291, in receive_json
    data = await self.receive_str(timeout=timeout)
  File "/home/chia/.local/share/virtualenvs/chia-monitor-Iocbb-0M/lib/python3.8/site-packages/aiohttp/client_ws.py", line 276, in receive_str
    raise TypeError(f"Received message {msg.type}:{msg.data!r} is not str")
TypeError: Received message 257:None is not str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chia/soft/chia-monitor/monitor/__main__.py", line 136, in <module>
    asyncio.run(aggregator(exporter, notifier))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/chia/soft/chia-monitor/monitor/collectors/ws_collector.py", line 91, in task
  File "/usr/lib/python3.8/logging/__init__.py", line 1458, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1085, in emit
    msg = self.format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 929, in format
    return fmt.format(record)
  File "/home/chia/.local/share/virtualenvs/chia-monitor-Iocbb-0M/lib/python3.8/site-packages/colorlog/colorlog.py", line 135, in format
    message = super(ColoredFormatter, self).format(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 670, in format
    record.asctime = self.formatTime(record, self.datefmt)
  File "/usr/lib/python3.8/logging/__init__.py", line 606, in formatTime
    ct = self.converter(record.created)
KeyboardInterrupt`

**Comment by tangdasan** [comment]
I have three full nodes, only this one can work normally

**Comment by charnet3d** [comment]
While waiting for my Pull Request to get merged you can try editing the file "monitor/collectors/ws_collector.py". Change the line:

```
self.ws = await self.session.ws_connect(f"wss://{self_hostname}:{daemon_port}",
                                                    ssl_context=self.ssl_context)
```

to:

```
self.ws = await self.session.ws_connect(f"wss://{self_hostname}:{daemon_port}",
                                                    ssl_context=self.ssl_context, max_msg_size=52428800)
```

And report if it does in fact fix the issue. Thanks.

**Comment by tangdasan** [comment]
It looks normal now. I'll observe it for some time. Thank you very much

**Comment by philippnormann** [comment]
Fixed in https://github.com/philippnormann/chia-monitor/commit/6ff3a230bd3b4fc065f0dbb9327909e387c5573a
