### ISSUE TITLE
Installation small chia imitation, Ya Yasushi unsuccessful

### ISSUE THREAD

**Issue by 774406683** [philippnormann/chia-monitor#5]
Installation small chia imitation, Ya Yasushi unsuccessful

**Comment by 774406683** [comment]
The chia module cannot be installed, and it is missing to start

**Comment by 774406683** [comment]
An error occurred while installing git+git://github.com/Chia-Network/chia-blockchain.git@2335beff151eeb743be4b81f625e175bea71f607#egg=chia-blockchain! Will try again.

**Comment by 774406683** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/chia-monitor/monitor/__main__.py", line 7, in <module>
    from chia.util.config import load_config
ModuleNotFoundError: No module named 'chia'

**Comment by philippnormann** [comment]
I also ran into this issue once and it resolved itself after I ran `pipenv install` again. 
Can you please retry running the update procedure using the latest version?

**Comment by 774406683** [comment]
![Uploading 截屏2021-07-09 10.56.36.png…]()

**Comment by 774406683** [comment]
(chia-monitor-ccPwOptf) mixchain@mixchain:/chia-monitor$ pipenv run python -m monitor
2021-07-09T02:53:20.449 ERROR  Unparseable Telegram URL tgram://{bot_token}/{chat_id}/
2021-07-09T02:53:20.449 ERROR  Unparseable Telegram URL tgram://{bot_token}/{chat_id}/
2021-07-09T02:53:20.450 INFO   🔌 Creating RPC Collector...
2021-07-09T02:53:20.453 WARNING Failed to connect to full node RPC endpoint. Continuing without it. Cannot connect to host 0.0.0.0:8555 ssl:<ssl.SSLContext object at 0x7fbe765584c0> [Connect call failed ('0.0.0.0', 8555)]
2021-07-09T02:53:20.454 WARNING Failed to connect to wallet RPC endpoint. Continuing without it. Cannot connect to host 0.0.0.0:9256 ssl:<ssl.SSLContext object at 0x7fbe765585c0> [Connect call failed ('0.0.0.0', 9256)]
2021-07-09T02:53:20.455 WARNING Failed to connect to farmer RPC endpoint. Continuing without it. Cannot connect to host 0.0.0.0:8559 ssl:<ssl.SSLContext object at 0x7fbe76558740> [Connect call failed ('0.0.0.0', 8559)]
2021-07-09T02:53:20.455 WARNING Failed to create RPC collector. Continuing without it. Failed to connect to any RPC endpoints, Check if your Chia services are running
2021-07-09T02:53:20.455 INFO   🔌 Creating WebSocket Collector...
2021-07-09T02:53:20.461 ERROR  Failed to create any collector.
2021-07-09T02:53:20.461 INFO   🛑 Shutting down!
-------------------------
How to solve this problem @philippnormann

**Comment by 774406683** [comment]
mixchain@mixchain:/chia-monitor$ sudo pipenv run python -m monitor
can't find /root/.chia/mainnet/config/config.yaml
** please run `chia init` to migrate or create new config files **
---------------------------------------------------
This directory should be wrong, it should be /.chai/mainnet/config/config.yaml
How can I search for this directory when modifying the run?

**Comment by 774406683** [comment]
mixchain@mixchain:~/.chia/mainnet/config$ ls
config.yaml  ssl
mixchain@mixchain:~/.chia/mainnet/config$ pwd
/home/mixchain/.chia/mainnet/config
-------------------------------
This is my chia configuration file directory

**Comment by philippnormann** [comment]
You are running the chia monitor as root and that's why it can't find your config. Try running it as a normal user.

**Comment by 774406683** [comment]
Does this have to be run on the famer node?

**Comment by 774406683** [comment]
(chia-monitor-ccPwOptf) mixchain@mixchain:/chia-monitor$ pipenv run python -m monitor
2021-07-09T02:53:20.449 ERROR Unparseable Telegram URL tgram://{bot_token}/{chat_id}/
2021-07-09T02:53:20.449 ERROR Unparseable Telegram URL tgram://{bot_token}/{chat_id}/
2021-07-09T02:53:20.450 INFO 🔌 Creating RPC Collector...
2021-07-09T02:53:20.453 WARNING Failed to connect to full node RPC endpoint. Continuing without it. Cannot connect to host 0.0.0.0:8555 ssl:<ssl.SSLContext object at 0x7fbe765584c0> [Connect call failed ('0.0.0.0', 8555)]
2021-07-09T02:53:20.454 WARNING Failed to connect to wallet RPC endpoint. Continuing without it. Cannot connect to host 0.0.0.0:9256 ssl:<ssl.SSLContext object at 0x7fbe765585c0> [Connect call failed ('0.0.0.0', 9256)]
2021-07-09T02:53:20.455 WARNING Failed to connect to farmer RPC endpoint. Continuing without it. Cannot connect to host 0.0.0.0:8559 ssl:<ssl.SSLContext object at 0x7fbe76558740> [Connect call failed ('0.0.0.0', 8559)]
2021-07-09T02:53:20.455 WARNING Failed to create RPC collector. Continuing without it. Failed to connect to any RPC endpoints, Check if your Chia services are running
2021-07-09T02:53:20.455 INFO 🔌 Creating WebSocket Collector...
2021-07-09T02:53:20.461 ERROR Failed to create any collector.
2021-07-09T02:53:20.461 INFO 🛑 Shutting down!
--------------------------
How to solve this error？

**Comment by philippnormann** [comment]
> Does this have to be run on the famer node?

Yes. The error indicates that you are not running the monitor on your farming machine.

**Comment by 774406683** [comment]
thank you
