### ISSUE TITLE
Failed to persist event in DB

### ISSUE THREAD

**Issue by nothingshocking** [philippnormann/chia-monitor#66]
Hi - I've been running chia-monitor on my RPi4 farmer (Ubuntu 21.04) for a few months now. I've noticed this issue/error recently. When it has happened in the past I have run the 'pipenv run alembic upgrade head' and restarted just fine but within a few days or even within the day the error occurs again. I've also removed the DB and started fresh but this has re-occurred. Are there any insights into the error that you can share or further steps in research you suggest? 

`2022-02-27T22:50:15.922 ERROR  Failed to persist event to DB. Please initialize DB using: 'pipenv run alembic upgrade head'
Traceback (most recent call last):
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 998, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 672, in do_commit
    dbapi_connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/******/chia-monitor/monitor/__main__.py", line 81, in aggregator
    persist_event(event)
  File "/home/******/chia-monitor/monitor/__main__.py", line 40, in persist_event
    db_session.commit()
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1428, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 836, in commit
    trans.commit()
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2361, in commit
    self._do_commit()
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2544, in _do_commit
    self._connection_commit_impl()
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2515, in _connection_commit_impl
    self.connection._commit_impl()
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1000, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 998, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/home/******/.local/share/virtualenvs/chia-monitor-jOrTMuHc/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 672, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
(Background on this error at: https://sqlalche.me/e/14/e3q8)
2022-02-27T22:50:15.994 INFO    Shutting down!
`

**Comment by nothingshocking** [comment]
The same error happened overnight. Not sure what is going on but it is recurring quite a bit.

**Comment by nothingshocking** [comment]
Issue occurred again, anyone else experience this or similar problem?

**Comment by nothingshocking** [comment]
The issue has persisted and happens so often I have stopped using chia-monitor. I really liked the tool.

**Comment by baerrs** [comment]
I'm having the same issue on a headless system.. no chia-monitor
